[workspace]
resolver = "2"
members = [
    "extensions/xtop-extension-mcp",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.87"

[workspace.dependencies]
xtop-extension-api = { git = "https://github.com/xtop-cli/api" }
xtop-plugin-samurai = { git = "https://github.com/xtop-cli/plugins" }
